### ISSUE TITLE
Validation complains about valid directory mode of 2775

### ISSUE THREAD

**Issue by pghalliday** [sethvargo/chefspec#375]
I get this error when trying to test a cookbook that depends on the rbenv cookbook. I have never seen this error from a real chef run and the mode was added in August 2013.

```
C:/Ruby193/bin/ruby.exe -S rspec ./spec/recipes/default_spec.rb
Using chef-build (0.1.0)
Using rbenv (1.7.1)
Using git (3.0.0)
Using dmg (2.2.0)
Using build-essential (1.4.4)
Using windows (1.30.0)
Using chef_handler (1.1.5)
Using runit (1.4.0)
Using yum (3.1.2)
Using yum-epel (0.3.4)
Using apt (2.3.8)
Using ohai (1.1.12)

================================================================================
Recipe Compile Error in C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/chef-build/recipes/default.rb
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option mode's value 2775 not in valid numeric range!

Cookbook Trace:
---------------
  C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/rbenv/recipes/default.rb:91:in `block in from_file'
  C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/rbenv/recipes/default.rb:88:in `from_file'
  C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/chef-build/recipes/default.rb:3:in `from_file'

Relevant File Content:
----------------------
C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/rbenv/recipes/default.rb:

 84:    supports :manage_home => node[:rbenv][:manage_home]
 85:    home node[:rbenv][:user_home]
 86:  end
 87:
 88:  directory node[:rbenv][:root] do
 89:    owner node[:rbenv][:user]
 90:    group node[:rbenv][:group]
 91>>   mode "2775"
 92:    recursive true
 93:  end
 94:
 95:  with_home_for_user(node[:rbenv][:user]) do
 96:
 97:    git node[:rbenv][:root] do
 98:      repository node[:rbenv][:git_repository]
 99:      reference node[:rbenv][:git_revision]
100:      user node[:rbenv][:user]

F

Failures:

  1) chef-build::default should configure a ruby build environment
     Failure/Error: let(:chef_run) { ChefSpec::Runner.new.converge(described_recipe) }
     Chef::Exceptions::ValidationFailed:
       Option mode's value 2775 not in valid numeric range!
     # C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/rbenv/recipes/default.rb:91:in `block in from_file'
     # C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/rbenv/recipes/default.rb:88:in `from_file'
     # C:/Users/PHALLI~1/AppData/Local/Temp/d20140310-4036-pnfc2r/cookbooks/chef-build/recipes/default.rb:3:in `from_file'
     # ./spec/recipes/default_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/recipes/default_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 19.14 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/recipes/default_spec.rb:10 # chef-build::default should configure a ruby build environment
C:/Ruby193/bin/ruby.exe -S rspec ./spec/recipes/default_spec.rb failed

C:\Development\lgcoreapps-cookbooks\chef-build>
```

**Comment by username-is-already-taken2** [comment]
Hi there, I appreciate this is an old thread but I'm a little lost to how to resolve this issue as I have come across today.  ```Option mode's value 2775 not in valid numeric range!``` I'm on windows and my runner is ```runner = ChefSpec::ServerRunner.new(platform: 'redhat', version: '6.3')```  I would appreciate your help I'm pretty new to chefspec

**Comment by pghalliday** [comment]
@username-is-already-taken2 I believe my solution was to stop using windows. I don't know if there are other options now that it's 3 years later
