### ISSUE TITLE
Support for Data bags in ChefSpec

### ISSUE THREAD

**Issue by proffalken** [sethvargo/chefspec#52]
Hi,

I'm trying to test a cookbook that uses a DataBag for certain variables however everytime I run rspec I get the following error:

```
[2012-09-25T15:59:05+01:00] ERROR: Failed to load data bag item: "ntp_data" "configs"
F[2012-09-25T15:59:05+01:00] ERROR: Failed to load data bag item: "ntp_data" "configs"
F

Failures:

  1) ntp::default should install ntp
     Failure/Error: let (:chef_run) { ChefSpec::ChefRunner.new.converge 'ntp::default'}
     Chef::Exceptions::InvalidDataBagPath:
       Data bag path '/var/chef/data_bags' is invalid
     # ./recipes/default.rb:16:in `from_file'
     # ./spec/default_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/default_spec.rb:6:in `block (2 levels) in <top (required)>'

  2) ntp::default should configure ntp
     Failure/Error: let (:chef_run) { ChefSpec::ChefRunner.new.converge 'ntp::default'}
     Chef::Exceptions::InvalidDataBagPath:
       Data bag path '/var/chef/data_bags' is invalid
     # ./recipes/default.rb:16:in `from_file'
     # ./spec/default_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/default_spec.rb:9:in `block (2 levels) in <top (required)>'

Finished in 0.00893 seconds
2 examples, 2 failures

Failed examples:

rspec ./spec/default_spec.rb:5 # ntp::default should install ntp
rspec ./spec/default_spec.rb:8 # ntp::default should configure ntp
```

My Spec looks as follows:

``` ruby
require 'chefspec'

describe 'ntp::default' do
  let (:chef_run) { ChefSpec::ChefRunner.new.converge 'ntp::default'}
  it 'should install ntp' do
    chef_run.should install_package "ntp"
  end
  it 'should configure ntp' do
    chef_run.should create_file "/etc/ntp.conf"
  end
end
```

and the recipe looks like this:

``` ruby
## install and configure NTP
package "ntp" do
  action :install
end

## we get our NTP configuration from a data bag, so let's load it here
ntp_data = data_bag_item("ntp_data","configs")

template "/etc/ntp.conf" do
  source "ntp.conf.erb"
  owner  "root"
  group  "root"
  mode   0644
  variables(
  :ntp_servers => ntp_data['servers']
  )
end
```

I realise that there are other NTP cookbooks around, however I'd like to use this simple example to learn how to use Data Bags in ChefSpec.

Thanks,

Matt

**Comment by bbc88ks** [comment]
> before do
>   cookbook_root = File.expand_path('../../',  __FILE__)
>   Chef::Config[:data_bag_path] = File.join(cookbook_root, '.data_bags')
> end

I can't get this to work, it doesn't upload the cookbooks from the folder using ServerRunner

Any ideas?

**Comment by daksha25** [comment]
Hi,
I am getting the same error as 
 Compiling Cookbooks...
       [2018-02-15T09:27:21+00:00] ERROR: Failed to load data bag item: "jira" "jira"
       [2018-02-15T09:27:21+00:00] ERROR: Failed to load data bag item: "jira" "jira"

when trying to test cookbook with test kitchen.
I am using chef-zer and docker provider.
please help me with the samw.
