### ISSUE TITLE
ChefSpec fails when the recipe contains only "include_recipe"

### ISSUE THREAD

**Issue by ArjunHariharan** [sethvargo/chefspec#558]
ChefSpec fails when the recipe contains only "include_recipe" and no other resource.

Ex-  
demo::default
`````````
include_recipe 'demo::_first'
`````````
demo::_first
`````````
file '/tmp/demo'
````````````````
Spec- demo_spec.rb

``````````````````
require 'chefspec'

describe 'demo::default' do
  let(:chef_run) do
    ChefSpec::SoloRunner.new(platform: 'centos', version: '6.5')
      .converge(described_recipe)
  end

  it 'it calls _first recipe' do
    expect_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('demo::_first')
  end
end
````````````````````

Error

``````````````````
demo::default it calls _first recipe
     Failure/Error: Unable to find matching line from backtrace
       Exactly one instance should have received the following message(s) but didn't: include_recipe
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-mocks-3.1.3/lib/rspec/mocks/any_instance/recorder.rb:94:in `verify'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-mocks-3.1.3/lib/rspec/mocks/space.rb:69:in `block in verify_all'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-mocks-3.1.3/lib/rspec/mocks/space.rb:69:in `each_value'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-mocks-3.1.3/lib/rspec/mocks/space.rb:69:in `verify_all'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-mocks-3.1.3/lib/rspec/mocks.rb:45:in `verify'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/mocking_adapters/rspec.rb:23:in `verify_mocks_for_rspec'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:382:in `verify_mocks'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:373:in `run_after_example'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:167:in `block in run'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:329:in `with_around_example_hooks'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:149:in `run'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:490:in `block in run_examples'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `map'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `run_examples'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:453:in `run'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block (2 levels) in run_specs'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `map'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `load'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `<main>'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
     # /Users/Arjun/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

`````````````````

The above example depicts one of the test scenarios that one would come across while writing chef specs. There should be a method to handle such scenarios.

**Comment by sethvargo** [comment]
@ArjunHariharan you aren't actually running Chef anywhere...

```diff
require 'chefspec'

describe 'demo::default' do
  let(:chef_run) do
    ChefSpec::SoloRunner.new(platform: 'centos', version: '6.5')
      .converge(described_recipe)
  end

  it 'it calls _first recipe' do
    expect_any_instance_of(Chef::Recipe).to receive(:include_recipe).with('demo::_first')
+   chef_run
  end
end
```

`let` is lazy-loaded. For more information on RSpec's let block, [please see the documentation](https://relishapp.com/rspec/rspec-core/v/2-6/docs/helper-methods/let-and-let).

**Comment by ArjunHariharan** [comment]
@sethvargo  - Got it. Thanks a ton!!! :)

**Comment by yoshiwaan** [comment]
I found (possibly due to my own lack of understanding) that I had to place all of the stubbed include recipe checks inside a single it block that ended with chef_run or I would continue to get this error.
