### ISSUE TITLE
Stub does not appear to return a value

### ISSUE THREAD

**Issue by Xoph** [sethvargo/chefspec#561]
I am having an issue with a stub that does not appear to return a value. I am mocking reading a data bag and trying to return a hash with the id and a value in it, but when I try to reference an item in the hash that is supposed to be returned by the stub, it gives me an error that it is null.

I've put the ChefSpec output below along with the recipe, the spec file, and a library file that has the commands being stubbed. Let me know if you need any more information.

I am hoping you can help me resolve this issue, as I've tried a bunch of different things to no prevail.

Thank you in advance,

Christoph
GE Healthcare

ChefSpec output for DakotaWebSiteCreation-spec.rb
```
================================================================================
Recipe Compile Error in C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/
recipes/DakotaWebSiteCreation.rb
================================================================================

TypeError
---------
no implicit conversion of nil into String

Cookbook Trace:
---------------
  C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBagHelpe
rs.rb:4:in `join'
  C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBagHelpe
rs.rb:4:in `decryptDataBagItem'
  C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/recipes/DakotaWebSiteC
reation.rb:22:in `from_file'

Relevant File Content:
----------------------
C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBagHelpers
.rb:

  1:  class DataBagHelpers
  2:    def self.decryptDataBagItem(dataBag, dataBagItem)
  3:            commonParameters = Chef::DataBagItem.load(dataBag, 'common')
  4>>           keyFilePath = File.join(commonParameters['rst_package_path'], 'InstallAutomation\data_bags\chefdb.bin')
  5:            decryptionKey = Chef::EncryptedDataBagItem.load_secret(keyFilePath)
  6:            return Chef::EncryptedDataBagItem.load(dataBag, dataBagItem, decryptionKey)
  7:    end
  8:  end  9:

F
================================================================================
Recipe Compile Error in C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/
recipes/DakotaWebSiteCreation.rb
================================================================================

TypeError
---------
no implicit conversion of nil into String

Cookbook Trace:
---------------
  C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBagHelpe
rs.rb:4:in `join'
  C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBagHelpe
rs.rb:4:in `decryptDataBagItem'
  C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/recipes/DakotaWebSiteC
reation.rb:22:in `from_file'

Relevant File Content:
----------------------
C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBagHelpers
.rb:

  1:  class DataBagHelpers
  2:    def self.decryptDataBagItem(dataBag, dataBagItem)
  3:            commonParameters = Chef::DataBagItem.load(dataBag, 'common')
  4>>           keyFilePath = File.join(commonParameters['rst_package_path'], 'InstallAutomation\data_bags\chefdb.bin')
  5:            decryptionKey = Chef::EncryptedDataBagItem.load_secret(keyFilePath)
  6:            return Chef::EncryptedDataBagItem.load(dataBag, dataBagItem, decryptionKey)
  7:    end
  8:  end  9:

F

Failures:

  1) rst-powershell-automation::DakotaWebSiteCreation includes the default recipe
     Failure/Error: let(:chef_run) { ChefSpec::Runner.new.converge(described_recipe) }
     TypeError:
       no implicit conversion of nil into String
     # C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBag
Helpers.rb:4:in `join'
     # C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBag
Helpers.rb:4:in `decryptDataBagItem'
     # C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/recipes/DakotaWeb
SiteCreation.rb:22:in `from_file'
     # ./spec/DakotaWebSiteCreation-spec.rb:24:in `block (2 levels) in <top (required)>'
     # ./spec/DakotaWebSiteCreation-spec.rb:44:in `block (2 levels) in <top (required)>'

  2) rst-powershell-automation::DakotaWebSiteCreation Runs DakotaWebSiteCreation.ps1
     Failure/Error: let(:chef_run) { ChefSpec::Runner.new.converge(described_recipe) }
     TypeError:
       no implicit conversion of nil into String
     # C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBag
Helpers.rb:4:in `join'
     # C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/libraries/DataBag
Helpers.rb:4:in `decryptDataBagItem'
     # C:/Users/212327~1/AppData/Local/Temp/d20150205-9720-15zd0c9/cookbooks/rst-powershell-automation/recipes/DakotaWeb
SiteCreation.rb:22:in `from_file'
     # ./spec/DakotaWebSiteCreation-spec.rb:24:in `block (2 levels) in <top (required)>'
     # ./spec/DakotaWebSiteCreation-spec.rb:48:in `block (2 levels) in <top (required)>'

Finished in 1.34 seconds (files took 43.8 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/DakotaWebSiteCreation-spec.rb:43 # rst-powershell-automation::DakotaWebSiteCreation includes the default re
cipe
rspec ./spec/DakotaWebSiteCreation-spec.rb:47 # rst-powershell-automation::DakotaWebSiteCreation Runs DakotaWebSiteCreat
ion.ps1

  No Chef resources found, skipping coverage calculation...
```

recipes\DakotaWebSiteCreation.rb:
```
include_recipe 'rst-powershell-automation'

scriptName = 'DakotaWebSiteCreation'
scriptParameters = [
	'Port',
	'Protocol',
	'SiteNas',
	'NasUserName',
	'NasPassword']
	
commonParameters = data_bag_item('rst-script-parameters', 'common')
scriptParametersDataBag = DataBagHelpers.decryptDataBagItem('rst-script-parameters', scriptName)

scriptParameterString = CreatePSScriptParameterString(scriptParameters, scriptParametersDataBag)

rst_common_powershellscriptex scriptName do
	action :run
	cwd commonParameters['rst_package_path']
	code ".\\#{scriptName}.ps1 -Silent#{scriptParameterString}"
end
```

spec\DakotaWebSiteCreation-spec.rb:
```
require_relative '..\..\..\lib\spec_helper'

dataBag = 'rst-script-parameters'
scriptName = 'DakotaWebSiteCreation'
rstPackagePath = "C:\\Support\\RST\\"
port = 85
protocol = 'http'
siteNas = 'Y'
nasUserName = 'username'
nasPassword = 'password'
commonDataBagItem = {
	id: 'common',
	rst_package_path: rstPackagePath
}

describe "rst-powershell-automation::#{scriptName}" do
	let(:chef_run) { ChefSpec::Runner.new.converge(described_recipe) }

	before do
		mock_include_recipe
		stub_data_bag_item(dataBag, 'common').and_return(commonDataBagItem)
		allow(Chef::DataBagItem).to receive(:load).with(dataBag, 'common').and_return(commonDataBagItem)
		allow(Chef::EncryptedDataBagItem).to receive(:load_secret).with('C:\Support\RST\InstallAutomation\data_bags\chefdb.bin').and_return('unit_test_key')
		allow(Chef::EncryptedDataBagItem).to receive(:load).with(dataBag, scriptName, 'unit_test_key').and_return(
		{
			id: scriptName,
			Port: port,
			Protocol: protocol,
			SiteNas: siteNas,
			NasUserName: nasUserName,
			NasPassword: nasPassword
		})
		
	end

	it "includes the default recipe" do
		expect(chef_run).to include_recipe('rst-powershell-automation')		
	end

	it "Runs #{scriptName}.ps1" do
		expect(chef_run).to run_PowershellScriptEx(scriptName).with(
			code: ".\\#{scriptName}.ps1 -Silent"\
				  " -Port #{port}"\
				  " -Protocol \"#{protocol}\""\
				  " -SiteNas \"#{siteNas}\""\
				  " -NasUserName \"#{nasUserName}\""\
				  " -NasPassword \"#{nasPassword}\"",
			cwd: rstPackagePath)
	end
end
```

libraries\DataBagHelpers.rb:
```
class DataBagHelpers
	def self.decryptDataBagItem(dataBag, dataBagItem)
		commonParameters = Chef::DataBagItem.load(dataBag, 'common')
		keyFilePath = File.join(commonParameters['rst_package_path'], 'InstallAutomation\data_bags\chefdb.bin')
		decryptionKey = Chef::EncryptedDataBagItem.load_secret(keyFilePath)
		return Chef::EncryptedDataBagItem.load(dataBag, dataBagItem, decryptionKey)
	end
end
```

**Comment by sethvargo** [comment]
I think this is a classic case of symbol vs string keys... You have:

```ruby
commonDataBagItem = {
    id: 'common',
    rst_package_path: rstPackagePath
}
```

That is the equivalent of:

```ruby
commonDataBagItem = {
    :id => 'common',
    :rst_package_path => rstPackagePath
}
```

Yet you have:

```ruby
keyFilePath = File.join(commonParameters['rst_package_path'], 'InstallAutomation\data_bags\chefdb.bin')
```

But `commonParameters["STRING KEY"]` is going to return `nil`, since you have Symbol keys. In effect, you have:

```ruby
File.join(nil, 'InstallAutomation\data_bags\chefdb.bin')
```

Which is why that error is happening. Switch to string keys and I bet your error will go away. Data bags are string keys anyway.

**Comment by Xoph** [comment]
Ok, that fixed it! Thank you so much. I'm thrown off by Ruby/Chef data types since I'm new to it all.

So why can I use commonParameters['rst_package_path'] in my recipe and it works fine there?

**Comment by sethvargo** [comment]
One is a Hash, one is a Mash. Hashes are hashes/maps/dictionaries - they are key-value pairs. Mashes are super-hashes that coerce keys into a particular type.

```ruby
# Hash
obj = Object.new
h = { "foo" => "bar", :zip => "zap", obj => "bacon" }
h["foo"] #=> "bar"
h[:foo] #=> nil
h.foo #=> NoMethodError
h[:zip] #=> "zap"
h["zip"] #=> nil
h[obj] #=> "bacon"
```

```ruby
# Mash
obj = Object.new
h = Mash.new("foo" => "bar", :zip => "zap", obj => "bacon")
h["foo"] #=> "bar"
h[:foo] #=> "bar"
h.foo #=> "bar"
h[:zip] #=> "zap"
h["zip"] #=> "zap"
h.zip #=> "zap"
h[obj] #=> "bacon"
```

**Comment by Xoph** [comment]
Thank you for the info!
