### ISSUE TITLE
undefined method `rights' for Chef::Resource::Directory

### ISSUE THREAD

**Issue by jmccann** [sethvargo/chefspec#575]
I have a test for a cookbook meant to be ran on Windows that tests fine on a Windows desktop but will fail on Mac OSX.  This is using chefspec 4.2.0.

Have some chefspec tests create directories for windows.

```ruby
directory 'C:\Temp' do
  rights :read_execute, 'Users', applies_to_children: true
  rights :full_control, 'Administrators', applies_to_children: true
  inherits true
end
```

With a spec of:
```ruby
  it 'creates temp folder in root of c drive' do
    expect(chef_run).to create_directory('C:\\Temp')
  end
```

And get

```
================================================================================
Recipe Compile Error in /var/folders/b8/px794xjj0_50p4ncpdpsl755d2vmx4/T/d20150324-70603-q65ln/cookbooks/testit/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `rights' for Chef::Resource::Directory

Cookbook Trace:
---------------
  /var/folders/b8/px794xjj0_50p4ncpdpsl755d2vmx4/T/d20150324-70603-q65ln/cookbooks/testit/recipes/default.rb:2:in `block in from_file'
  /var/folders/b8/px794xjj0_50p4ncpdpsl755d2vmx4/T/d20150324-70603-q65ln/cookbooks/testit/recipes/default.rb:1:in `from_file'

Relevant File Content:
----------------------
/var/folders/b8/px794xjj0_50p4ncpdpsl755d2vmx4/T/d20150324-70603-q65ln/cookbooks/testit/recipes/default.rb:

  1:  directory 'C:\Temp' do
  2>>   rights :read_execute, 'Users', applies_to_children: true
  3:    rights :full_control, 'Administrators', applies_to_children: true
  4:    inherits true
  5:  end
  6:  

F

Failures:

  1) testit::default creates temp folder in root of c drive
     Failure/Error: ChefSpec::ServerRunner.new.converge(described_recipe)
     NoMethodError:
       undefined method `rights' for Chef::Resource::Directory
     # /var/folders/b8/px794xjj0_50p4ncpdpsl755d2vmx4/T/d20150324-70603-q65ln/cookbooks/testit/recipes/default.rb:2:in `block in from_file'
     # /var/folders/b8/px794xjj0_50p4ncpdpsl755d2vmx4/T/d20150324-70603-q65ln/cookbooks/testit/recipes/default.rb:1:in `from_file'
     # ./spec/default_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/default_spec.rb:9:in `block (2 levels) in <top (required)>'
```

**Comment by rhb84** [comment]
I have similar issue but on Linux, when I ran the tests on Windows  - all is ok, on Linux I get the above error. I'm running latest version of ChefDK and also updated chefspec gem to 4.3.0 - same issue.

Here are some details about my setup:
```
[root@localhost gems]# chef -v
Chef Development Kit Version: 0.6.2
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0
[root@localhost gems]# chef exec gem list --local | grep chefspec
chefspec (4.3.0)
[root@localhost gems]#
```

The error I get:

```
F
================================================================================
Recipe Compile Error in /tmp/d20150730-13691-1rer4f0/cookbooks/windows_cb/recipes/windows.rb
================================================================================

NoMethodError
-------------
undefined method `rights' for Chef::Resource::Directory
```

relevant part of recipe:
```
 13:  directory 'C:\\Program Files\\WindowsPowerShell\\Modules\\Test_Dir' do
 14>>   rights :full_control, 'everyone'
```

Spec:
```
 13:  directory 'C:\\Program Files\\WindowsPowerShell\\Modules\\Test_Dir' do
 14>>   rights :full_control, 'everyone'
```
