### ISSUE TITLE
ERROR: Failed to load data bag item: "auth" "default"

### ISSUE THREAD

**Issue by dgoradia-atlas** [sethvargo/chefspec#587]
I'm getting a `Net::HTTPServerException 404 "Not Found "` using ServerRunner

##### Recipe - default.rb
    node.default['default']['databag'] = data_bag_item('auth', 'default')
    
    template '/root/.ssh/authorized_keys' do
      source 'authorized_keys.erb'
      owner 'root'
      group 'root'
      mode '0600'

      variables(:public_keys => node.default['default']['databag']['public_keys'])
    end

##### Spec - default_spec.rb
Taken the example from: https://github.com/sethvargo/chefspec/blob/master/examples/stub_data_bag_item/spec/default_spec.rb
    
    require_relative '../spec_helper'

    describe 'kvm::default' do
      subject { ChefSpec::ServerRunner.new.converge(described_recipe) }

      let(:chef_run) { ChefSpec::ServerRunner.new.converge(described_recipe) }

      # Default auth data bag
      context 'default data bag' do
        it 'loads public keys' do
          stub_data_bag_item("auth", "default").and_return({ id: 'default', public_keys: '[
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOCVhIb7/MSN5nrj50ZABzrb1PuNy/xhakcg+OFVb7Mki2jrAza9Usbak1GuOCydLhca0GcQFbVZ1t70l8CH2hGIFcQ0vllgGgadUN+gyA+FrC/JqkFhyizTkGmOaK8f8U2254SHGj9jdfcDc7r5y+wjahAp4yrQT5x1IZJwcwkIF7mTeni4h6wO9lgOac4TDHFSG/KNZ6fVfAR2KgcsFurskCcd5IsxhXG5FEJQd9vXLTXHYi7vLLweFyr0yUplGVyyTLcIh3g2IIGDw4hX7BBsvYLoE8zvzI9YGoV6ihbSG41LeDzTbAIOa7QEGwmKyBYe4fIVUaEUd9H9XMXE0L email@example.com"
      ]' })
          expect(chef_run).to_not raise_error
        end
      end
    end

##### Trace
```
dgoradia@dgoradia-mbpro:~/chef-repo/cookbooks/kvm$ bundle exec rspec -b
[2015-04-20T13:32:08-07:00] ERROR: Failed to load data bag item: "auth" "default"

================================================================================
Recipe Compile Error in /var/folders/sc/_qzj689n2pn21phy1zh12q800000gn/T/d20150420-8273-1olnol2/cookbooks/kvm/recipes/default.rb
================================================================================

Net::HTTPServerException
------------------------
404 "Not Found "

Cookbook Trace:
---------------
  /var/folders/sc/_qzj689n2pn21phy1zh12q800000gn/T/d20150420-8273-1olnol2/cookbooks/kvm/recipes/default.rb:11:in `from_file'

Relevant File Content:
----------------------
/var/folders/sc/_qzj689n2pn21phy1zh12q800000gn/T/d20150420-8273-1olnol2/cookbooks/kvm/recipes/default.rb:

  4:  #
  5:  # Copyright 2015, Atlas Digital LLC
  6:  #
  7:  # All rights reserved - Do Not Redistribute
  8:  #
  9:  
 10:  # 1. Load Data Bags
 11>> node.default['default']['databag'] = data_bag_item('auth', 'default')
 12:  #node.default['client']['info'] = data_bag_item('client', node['hostname'])
 13:  
 14:  # 2. Include recipes
 15:  #include_recipe 'yum'
 16:  #include_recipe 'resolver'
 17:  #include_recipe 'snmp'
 18:  #include_recipe 'iptables-ng'
 19:  #include_recipe '::iptables'  # depends: yum
 20:  #include_recipe '::networking'   # depends: resolver, snmp, ::default[snmp community]

F

Failures:

  1) kvm::default default data bag loads public keys
     Failure/Error: let(:chef_run) { ChefSpec::ServerRunner.new.converge(described_recipe) }
     Net::HTTPServerException:
       404 "Not Found "
     # /opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/http.rb:145:in `request'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/rest.rb:115:in `get'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/data_bag_item.rb:149:in `load'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/dsl/data_query.rb:62:in `data_bag_item'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chefspec-4.2.0/lib/chefspec/extensions/chef/data_query.rb:37:in `data_bag_item'
     # /var/folders/sc/_qzj689n2pn21phy1zh12q800000gn/T/d20150420-8273-1olnol2/cookbooks/kvm/recipes/default.rb:11:in `from_file'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/mixin/from_file.rb:30:in `from_file'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/cookbook_version.rb:245:in `load_recipe'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/run_context.rb:169:in `load_recipe'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/run_context.rb:92:in `load'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/client.rb:235:in `setup_run_context'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:115:in `converge'
     # /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chefspec-4.2.0/lib/chefspec/server_runner.rb:60:in `converge'
     # ./spec/recipes/default_spec.rb:6:in `block (2 levels) in <top (required)>'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/memoized_helpers.rb:242:in `block (2 levels) in let'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/memoized_helpers.rb:242:in `fetch'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/memoized_helpers.rb:242:in `block in let'
     # ./spec/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:177:in `instance_exec'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:177:in `block in run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:385:in `block in with_around_and_singleton_context_hooks'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:343:in `block in with_around_example_hooks'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:474:in `block in run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:612:in `run_around_example_hooks_for'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:474:in `run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:343:in `with_around_example_hooks'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:385:in `with_around_and_singleton_context_hooks'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:174:in `run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:549:in `block in run_examples'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:545:in `map'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:545:in `run_examples'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:512:in `run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `block in run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `map'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:110:in `block (3 levels) in run_specs'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:110:in `map'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:110:in `block (2 levels) in run_specs'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1526:in `with_suite_hooks'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:109:in `block in run_specs'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/reporter.rb:62:in `report'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:108:in `run_specs'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:86:in `run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/bin/rspec:23:in `load'
     # /Users/dgoradia/.chefdk/gem/ruby/2.1.0/bin/rspec:23:in `<main>'

Finished in 0.51189 seconds (files took 1.35 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/recipes/default_spec.rb:10 # kvm::default default data bag loads public keys
```

What am I doing wrong?

**Comment by sethvargo** [comment]
Hi @dgoradia-atlas 

Thank you for opening an issue. I would suggest reading the [Using a Chef Server](https://github.com/sethvargo/chefspec#using-a-chef-server) section of the documentation. You need to create the databag using the `create_data_bag` method in the server block, [example](https://github.com/sethvargo/chefspec/blob/dba9e2d250b78fe8a9304cd5a41cb497d4634167/examples/server/spec/data_bag_spec.rb).
