### ISSUE TITLE
ChefSpec 4.3 throws IOError Cannot open or read attributes/default.rb when stubbing ::File.exists?

### ISSUE THREAD

**Issue by dhoer** [sethvargo/chefspec#620]
When ::File.exists? is stubbed, ChefSpec 4.3 throws the stacktrace below.  ChefSpec 4.2.x doesn't.  

I have tested this issue on other cookbooks that have ::File.exists? stubbed and get the same error.
Please let me know if you need more information.

```
================================================================================
  Recipe Compile Error in /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20150730-30464-1viqxrb/cookbooks/privacy_services_manager/attributes/default.rb
================================================================================

  IOError
-------
Cannot open or read /var/folders/kl/1m4f0gbd62b7wgqb1tt6cg180000gn/T/d20150730-30464-1viqxrb/cookbooks/privacy_services_manager/attributes/default.rb!

Cookbook Trace:
    ---------------
    /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/mixin/from_file.rb:32:in `from_file'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/dsl/include_attribute.rb:31:in `each'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/run_context/cookbook_compiler.rb:181:in `load_attribute_file'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/run_context/cookbook_compiler.rb:170:in `load_attributes_from_cookbook'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/run_context/cookbook_compiler.rb:110:in `block in compile_attributes'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/run_context/cookbook_compiler.rb:109:in `each'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/run_context/cookbook_compiler.rb:109:in `compile_attributes'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/run_context.rb:89:in `load'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/client.rb:265:in `setup_run_context'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:115:in `converge'
  /Users/myuser/chef/cookbooks/privacy_services_manager/spec/unit/default_spec.rb:9:in `block (2 levels) in <top (required)>'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:295:in `block (2 levels) in let'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:157:in `block (3 levels) in fetch_or_store'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:157:in `fetch'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:157:in `block (2 levels) in fetch_or_store'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/reentrant_mutex.rb:22:in `synchronize'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:156:in `block in fetch_or_store'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:155:in `fetch'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:155:in `fetch_or_store'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:295:in `block in let'
/Users/myuser/chef/cookbooks/privacy_services_manager/spec/unit/default_spec.rb:13:in `block (2 levels) in <top (required)>'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
  /Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'

Relevant File Content:
----------------------
/Users/myuser/.rvm/gems/ruby-2.0.0-p643/gems/chef-11.18.12/lib/chef/mixin/from_file.rb:

 25:        # object.
 26:        #
 27:        # Raises an IOError if the file cannot be found, or is not readable.
 28:        def from_file(filename)
 29:          if File.exists?(filename) && File.readable?(filename)
 30:            self.instance_eval(IO.read(filename), filename, 1)
 31:          else
 32>>           raise IOError, "Cannot open or read #{filename}!"
 33:          end
 34:        end
 35:
 36:        # Loads a given ruby file, and runs class_eval against it in the context of the current
 37:        # object.
 38:        #
 39:        # Raises an IOError if the file cannot be found, or is not readable.
 40:        def class_from_file(filename)
 41:          if File.exists?(filename) && File.readable?(filename)
```

**Comment by sethvargo** [comment]
Spec please?

**Comment by dhoer** [comment]
```
require 'spec_helper'

describe 'privacy_services_manager::default' do
  before(:each) do
    allow(::File).to receive(:exists?).and_return(false)
  end

  let(:chef_run) do
    ChefSpec::SoloRunner.new(platform: 'mac_os_x', version: '10.10').converge(described_recipe)
  end

  it 'installs privacy_services_manager' do
    expect(chef_run).to install_dmg_package('Privacy Services Management [1.6.8]')
  end
end
```

**Comment by dhoer** [comment]
Opps, I lied, it is doing it for 4.2 as well.

**Comment by sethvargo** [comment]
@dhoer yea, you can't do that. That stubs all calls to `File.exists?` in the current Ruby context. You need to do something like this:

```ruby
allow(File).to receive(:exists?).and_call_original
allow(File).to receive(:exists?).and_return(false)
```

OR stub it specifically

```ruby
allow(File).to receive(:exists?).with("my_file").and_return(false)
```

**Comment by dhoer** [comment]
Doh!  I should have known that.  I was also tripped up by mixing `exist?` and `exists?` which means I'm getting to dependent rubocop to catch that.

**Comment by dhoer** [comment]
BTW, thanks for the quick response
