### ISSUE TITLE
Recipe Variable Not Being Initialized in ChefSpec Run

### ISSUE THREAD

**Issue by Bjorn248** [sethvargo/chefspec#622]
Basically I'm storing the results of an encrypted data bag call to a variable in my recipe and the unit test I have written so far does not seem to like that.

Recipe Snippet
```
credentials = Chef::EncryptedDataBagItem.load("stuff", "credentials")
variables({
    :aws_access_key_id => credentials['aws_s3']['accessKeyId'],
    :aws_secret_access_key => credentials['aws_s3']['secretAccessKey'],
    :gpgKey => credentials['aws_s3']['gpgKey']
})
```

ChefSpec Test
```
#
# Cookbook Name:: logrotate
# Spec:: s3cmd
#
# Copyright (c) 2015 The Authors, All Rights Reserved.

require 'spec_helper'

describe 'logrotate::s3cmd' do
  context 'When all attributes are default, on an unspecified platform' do
    let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }

    before do
        stub_command("which s3cmd").and_return(true)
        allow(Chef::EncryptedDataBagItem).to receive(:load).with('stuff', 'credentials').and_return(
            {
                aws_s3:
                    {
                        accessKeyId: 'stubbing',
                        secretAccessKey: 'for testing',
                        gpgKey: 'purposes'
                    }
            })
    end

    it 'installs epel' do
      expect(chef_run).to install_package('epel-release')
    end
    it 'installs the s3cmd package' do
        expect(chef_run).to run_bash('yum -y --enablerepo epel-testing install s3cmd').with(user: 'root')
    end
  end
end
```

Error as a result of running `rspec spec/unit/recipes/s3cmd_spec.rb`
```
================================================================================
Recipe Compile Error in /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:20:in `block in from_file'
  /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:13:in `from_file'

Relevant File Content:
----------------------
/tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:

 13:  template "/root/.s3cfg" do
 14:      source "s3cfg.erb"
 15:      mode 0600
 16:      owner "root"
 17:      group "root"
 18:    credentials = Chef::EncryptedDataBagItem.load("stuff", "credentials")
 19:    variables({
 20>>         :aws_access_key_id => credentials['aws_s3']['accessKeyId'],
 21:          :aws_secret_access_key => credentials['aws_s3']['secretAccessKey'],
 22:          :gpgKey => credentials['aws_s3']['gpgKey']
 23:    })
 24:  end
 25:

F
================================================================================
Recipe Compile Error in /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:20:in `block in from_file'
  /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:13:in `from_file'

Relevant File Content:
----------------------
/tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:

 13:  template "/root/.s3cfg" do
 14:      source "s3cfg.erb"
 15:      mode 0600
 16:      owner "root"
 17:      group "root"
 18:    credentials = Chef::EncryptedDataBagItem.load("stuff", "credentials")
 19:    variables({
 20>>         :aws_access_key_id => credentials['aws_s3']['accessKeyId'],
 21:          :aws_secret_access_key => credentials['aws_s3']['secretAccessKey'],
 22:          :gpgKey => credentials['aws_s3']['gpgKey']
 23:    })
 24:  end
 25:

F

Failures:

  1) logrotate::s3cmd When all attributes are default, on an unspecified platform installs epel
     Failure/Error: let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:20:in `block in from_file'
     # /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:13:in `from_file'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:115:in `converge'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:18:in `block in converge'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `tap'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `converge'
     # ./spec/unit/recipes/s3cmd_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/s3cmd_spec.rb:27:in `block (3 levels) in <top (required)>'

  2) logrotate::s3cmd When all attributes are default, on an unspecified platform installs the s3cmd package
     Failure/Error: let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:20:in `block in from_file'
     # /tmp/d20150810-17056-9m8bbt/cookbooks/logrotate/recipes/s3cmd.rb:13:in `from_file'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:115:in `converge'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:18:in `block in converge'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `tap'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.2.0/lib/chefspec/solo_runner.rb:17:in `converge'
     # ./spec/unit/recipes/s3cmd_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/s3cmd_spec.rb:30:in `block (3 levels) in <top (required)>'

Finished in 0.56839 seconds (files took 4.59 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/unit/recipes/s3cmd_spec.rb:26 # logrotate::s3cmd When all attributes are default, on an unspecified platform installs epel
rspec ./spec/unit/recipes/s3cmd_spec.rb:29 # logrotate::s3cmd When all attributes are default, on an unspecified platform installs the s3cmd package

  No Chef resources found, skipping coverage calculation...
```

Any help or advice on the matter would be greatly appreciated.

**Comment by sethvargo** [comment]
Symbol vs string keys. You're using strings in your recipe, but symbols in your test.

**Comment by Bjorn248** [comment]
Many thanks, that indeed did solve it!
