### ISSUE TITLE
node.runner not defined

### ISSUE THREAD

**Issue by h4ck3rm1k3** [sethvargo/chefspec#636]
On this line I am getting an exception that node.runner is not defined :
https://github.com/sethvargo/chefspec/blob/390bc436cf46de993716ac4a6002c9de230f710d/lib/chefspec/extensions/chef/resource.rb#L25

Using my test call here :
https://github.com/h4ck3rm1k3/application/blob/master/Makefile#L5

Here is the stack :
```
[2015-09-27T07:17:47-04:00] INFO: Processing ruby_block[subresource_order_fixer] action run (dynamically defined)

[2015-09-27T07:17:47-04:00] INFO: Running queued delayed notifications before re-raising exception
[2015-09-27T07:17:47-04:00] DEBUG: Re-raising exception: NoMethodError - Undefined method or attribute `runner' on `node'
/mnt/data/home/mdupont/experiments/chef/lib/chef/node/attribute.rb:477:in `method_missing'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/node.rb:295:in `method_missing'
  /mnt/data/home/mdupont/experiments/chefspec/lib/chefspec/extensions/chef/resource.rb:20:in `run_action'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/runner.rb:49:in `run_action'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/runner.rb:81:in `each'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/runner.rb:81:in `block in converge'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/runner.rb:80:in `converge'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/client.rb:653:in `block in converge'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/client.rb:648:in `catch'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/client.rb:648:in `converge'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/client.rb:687:in `converge_and_save'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/client.rb:269:in `run'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application.rb:258:in `fork'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application.rb:258:in `fork_chef_client'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application.rb:224:in `block in run_chef_client'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application.rb:212:in `run_chef_client'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application/solo.rb:269:in `loop'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application/solo.rb:247:in `run_application'
  /mnt/data/home/mdupont/experiments/chef/lib/chef/application.rb:60:in `run'
  /mnt/data/home/mdupont/experiments/chef/bin/chef-solo:25:in `<top (required)>'
  /var/lib/gems/2.1.0/bin/chef-solo:23:in `load'
  /var/lib/gems/2.1.0/bin/chef-solo:23:in `<main>'

Running handlers:
```

Here are the methods available at that point 
```
Looking for `runner' in attributes:
!
!=
!~
<=>
==
===
=~
[]
[]=
__id__
__send__
all?
any?
assoc
attribute?
automatic
automatic=
chunk
class
clear
clone
collect
collect_concat
combined_default
combined_override
compare_by_identity
compare_by_identity?
convert_key
convert_value
count
cycle
dclone
debug_value
deep_merge_cache
deep_merge_cache=
default
default!
default=
default_proc
default_proc=
define_singleton_method
delete
delete_if
deprecated
detect
display
drop
drop_while
dup
each
each_attribute
each_cons
each_entry
each_key
each_pair
each_slice
each_value
each_with_index
each_with_object
empty?
entries
enum_for
env_default
env_default=
env_override
env_override=
eql?
equal?
except
extend
fetch
ffi_yajl
find
find_all
find_index
first
flat_map
flatten
force_default
force_default!
force_default=
force_override
force_override!
force_override=
freeze
frozen?
gem
grep
group_by
has_key?
has_value?
hash
immutablize
include?
index
inject
inspect
instance_eval
instance_exec
instance_of?
instance_variable_defined?
instance_variable_get
instance_variable_set
instance_variables
invert
is_a?
keep_if
key
key?
keys
kind_of?
lazy
length
map
max
max_by
member?
merge
merge!
merged_attributes
method
method_missing
methods
min
min_by
minmax
minmax_by
nil?
none?
normal
normal!
normal=
object_id
one?
override
override!
override=
partition
pretty_inspect
pretty_print
pretty_print_cycle
pretty_print_inspect
pretty_print_instance_variables
private_methods
protected_methods
psych_to_yaml
public_method
public_methods
public_send
rassoc
reduce
regular_update
regular_writer
rehash
reject
reject!
remove_instance_variable
replace
reset
reset_cache
respond_to?
reverse_each
rm
rm_default
rm_normal
rm_override
role_default
role_default=
role_override
role_override=
save_plist
select
select!
send
set_unless?
set_unless_value_present=
shift
should
should_not
singleton_class
singleton_method
singleton_methods
size
slice_before
sort
sort_by
store
stringify_keys!
symbolize_keys
taint
tainted?
take
take_while
tap
to_a
to_enum
to_h
to_hash
to_json
to_plist
to_s
to_set
to_yaml
to_yaml_properties
top_level_breadcrumb
top_level_breadcrumb=
trust
untaint
untrust
untrusted?
update
value?
values
values_at
which
zip
```

**Comment by sethvargo** [comment]
@h4ck3rm1k3 the issue is that you are loading ChefSpec as part of the same bundle as a production Chef run, but not requiring it. This means Ruby is pulling in the monkey patches, but not the entire ChefSpec library. You should not run ChefSpec as part of the same bundle as a regular chef-solo run. Put one in a development group and then bundle --without.
