### ISSUE TITLE
Documentation for multipackage installs in Chef 12.1+

### ISSUE THREAD

**Issue by tas50** [sethvargo/chefspec#639]
I'm not seeing an example of how to test multipackage installs with Chef 12.1.  Is that supported in Chefspec?

**Comment by thenoid** [comment]
I've just run into this as well - would love some guidance.

Package provider allows for passing of an array: https://docs.chef.io/resource_package.html#multiple-packages.   Checking for each package to be installed fails, checking for the entire array passes.  While it makes sense, i do wish it was possible to check for a single package from the array.

## recipes/default.rb
```ruby
#
# Cookbook Name:: test
# Recipe:: default
#
# Copyright (c) 2015 The Authors, All Rights Reserved.
#
packages = %w(zsh vim bash)
package packages do
  action :install
end
```
## spec/unit//recipes/default_spec.rb
```ruby
#
# Cookbook Name:: test
# Spec:: default
#
# Copyright (c) 2015 The Authors, All Rights Reserved.

require 'spec_helper'

describe 'test::default' do
  context 'When all attributes are default, on an unspecified platform' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      chef_run # This should not raise an error
    end
    packages = %w(zsh vim bash)
    packages.each do |package|
      it "installs a #{package} with the default action" do
        expect(chef_run).to install_package(package)
      end
    end
    it "installs a bunch with the default action" do
      expect(chef_run).to install_package(packages)
    end
  end
end
```
## output
```bash
.FFF.

Failures:

  1) test::default When all attributes are default, on an unspecified platform installs a zsh with the default action
     Failure/Error: expect(chef_run).to install_package(package)
       expected "package[zsh]" with action :install to be in Chef run. Other package resources:

         package[zsh, vim, bash]

     # ./spec/unit/recipes/default_spec.rb:22:in `block (4 levels) in <top (required)>'

  2) test::default When all attributes are default, on an unspecified platform installs a vim with the default action
     Failure/Error: expect(chef_run).to install_package(package)
       expected "package[vim]" with action :install to be in Chef run. Other package resources:

         package[zsh, vim, bash]

     # ./spec/unit/recipes/default_spec.rb:22:in `block (4 levels) in <top (required)>'

  3) test::default When all attributes are default, on an unspecified platform installs a bash with the default action
     Failure/Error: expect(chef_run).to install_package(package)
       expected "package[bash]" with action :install to be in Chef run. Other package resources:

         package[zsh, vim, bash]

     # ./spec/unit/recipes/default_spec.rb:22:in `block (4 levels) in <top (required)>'

Finished in 0.62762 seconds (files took 5.94 seconds to load)
5 examples, 3 failures

Failed examples:

rspec ./spec/unit/recipes/default_spec.rb:21 # test::default When all attributes are default, on an unspecified platform installs a zsh with the default action
rspec ./spec/unit/recipes/default_spec.rb:21 # test::default When all attributes are default, on an unspecified platform installs a vim with the default action
rspec ./spec/unit/recipes/default_spec.rb:21 # test::default When all attributes are default, on an unspecified platform installs a bash with the default action

```

**Comment by ranjib** [comment]
@tas50 i dont think so. while we get something to address that, is it possible that you change the multipackage declaration like this:
```ruby
package 'foo' do
   package_name %w(x y z)
end
```
then you can test it as:
```ruby
expect(chef_run).to create_package('foo').with(
   package_name: %w(x y z)
)
```
this is a workaround, but has two benefit, 1) you get the spec going :-)  , 2) while logging chef run, it wont print all the package names as resource name, screwing the whole output

**Comment by sethvargo** [comment]
Hi @tas50 @thenoid 

If you take a look at the specs, you can see an example of testing with an array (examples/package/spec/install_spec.rb). In short, given:

```ruby
package ["foo", "bar"]
```

the associated test is:

```ruby
expect(chef_run).to install_package(["foo", "bar"])
```

**Comment by sethvargo** [comment]
It's important to note that the "resource" in this case is `package[foo, bar]` (which is also shown on the docs page). Since there is only one resource, you cannot iterate over the results of the package, since ChefSpec only sees it as a single resource. Does that make sense?

I'm going to close this issue, but I'm happy to continue the conversation.

**Comment by dragon788** [comment]
Did any of this affect options within `package`?

Currently when passing a String for `package` to `options` `chefspec` currently reports a fail as it is treating `options` like an array and NOT a string.

The below works with `[` but not without, even though the API docs definitely say `options` is a String (and not allowed to be an array).
```
  it 'install collectd' do
    expect(chef_run).to install_package('collectd').with(options: ['--no-install-recommends'])
  end
```

**Comment by coderanger** [comment]
@dragon788 1) don't necro old, closed issues. 2) Yes, Chef coerces that to an array to simplify handling.
