### ISSUE TITLE
question/advice testing recipes against OSX 

### ISSUE THREAD

**Issue by arukaen** [sethvargo/chefspec#649]
hi guys. 

Trying to write some tests for an OSX recipe and getting some funky errors. This is the first time I've tried to write these tests for OSX. 

```rb
# spec_helper.rb
require 'chefspec'
require 'chefspec/berkshelf'
require 'json'

RSpec.configure do |config|
  # Specify the Chef log_level (default: :warn)
  config.log_level = :error

  # Specify the operating platform to mock Ohai data from (default: nil)
  config.platform = 'mac_os_x'

  # Specify the operating version to mock Ohai data from (default: nil)
  config.version = '10.10.5'
end

Chef::Config[:data_bag_path] = "#{File.dirname(__FILE__)}/../test/integration/data_bags"
ChefSpec::Coverage.start!
```

```rb
#default_spec.rb
require 'spec_helper'

describe 'osx-sketchsync::default' do
    let(:chef_run) do
        ChefSpec::SoloRunner.new do |node|
          # Create a new environment (you could also use a different :let block or :before block)
            env = Chef::Environment.new
            env.name = testing
            
            # Stub the node to return this environment
            allow(node).to receive(:chef_environment).and_return(env.name)

            # Stub any calls to Environment.load to return this environment
            allow(Chef::Environment).to receive(:load).and_return(env)
        end.converge(describe_recipe)
    end

    it 'installs python via homebrew' do
        expect(chef_run).to install_package('python')
    end

end
````

```sh
#error
17:10 $ rspec spec/default_spec.rb
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
F

Failures:

  1) osx-app::default installs python via homebrew
     Failure/Error:
               ChefSpec::SoloRunner.new do |node|
                   env = Chef::Environment.new
                   env.name = testing

                   allow(node).to receive(:chef_environment).and_return(env.name)
                   allow(Chef::Environment).to receive(:load).and_return(env)
               end.converge(describe_recipe)

     Fauxhai::Exception::InvalidPlatform:
       Could not find platform 'mac_os_x/10.10.5' in any of the sources!
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:63:in `rescue in block in fauxhai_data'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:60:in `block in fauxhai_data'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:77:in `call'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:77:in `fauxhai_data'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:26:in `initialize'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai.rb:12:in `new'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai.rb:12:in `mock'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.4.0/lib/chefspec/solo_runner.rb:373:in `client'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.4.0/lib/chefspec/solo_runner.rb:141:in `node'
     # /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.4.0/lib/chefspec/solo_runner.rb:84:in `initialize'
     # ./spec/default_spec.rb:5:in `new'
     # ./spec/default_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/default_spec.rb:20:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenURI::HTTPError:
     #   404 Not Found
     #   /Users/crisg/.chefdk/gem/ruby/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/mocker.rb:61:in `block in fauxhai_data'

Finished in 2.15 seconds (files took 24 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/default_spec.rb:19 # osx-app::default installs python via homebrew


  No Chef resources found, skipping coverage calculation...
```

**Comment by kierenevans** [comment]
Hi,

It's likely due to Fauxhai not having the 10.10.5 definition. Have a look in https://github.com/customink/fauxhai/tree/master/lib/fauxhai/platforms/mac_os_x 

So I guess either try using a version already defined, or put in a PR to define one :)

**Comment by arukaen** [comment]
Thanks that totally helped out. :+1:
