### ISSUE TITLE
Unable to utilize chefspec with an http proxy

### ISSUE THREAD

**Issue by mickfeech** [sethvargo/chefspec#667]
If the HTTP_PROXY variable is set a chefspec runs with the following failure.  

```
Failure/Error: expect { chef_run }.to_not raise_error
  expected no Exception, got #<Net::HTTPFatalError: 504 "Gateway Timeout"> with backtrace:
    # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
    # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
    # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
```

If HTTP_PROXY is unset and the cookbook / recipe needs to reach out to the internet (assuming you are behing a proxy) you receive the following errors

```
     Failure/Error: expect { chef_run }.to_not raise_error
       expected no Exception, got #<Errno::ETIMEDOUT: A connection attempt failed because the connected party did not properly res
pond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "raw.
github.com" port 443> with backtrace:
         # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
```

**Comment by sethvargo** [comment]
Hi @mickfeech 

ChefSpec does not read the `HTTP(S)_PROXY` environment variables because it does not connect to the Internet. This is most likely a Chef Client issue, since that is what is executed under the hood. I dug though Chef's codebase and it looks like they are correctly listening to the environment variables. Are you able to share your recipes and perhaps more log output?

**Comment by sethvargo** [comment]
Closing due to inactivity
