### ISSUE TITLE
ChefSpec and Policyfiles in Chef 12.10.24

### ISSUE THREAD

**Issue by mcquin** [sethvargo/chefspec#716]
Hellos, I'm having difficulty with ChefSpec and Policyfiles on Chef 12.10.24. I'm testing a cookbook that does not use Policyfiles, yet ChefSpec/Chef is trying to require/use Policyfiles.

When I set up a test with `ChefSpec::SoloRunner.converge(described_recipe)` I get:

```
================================================================================
Chef encountered an error attempting to load the node data for "fauxhai.local"
================================================================================

Unexpected Error:
-----------------
Chef::PolicyBuilder::Policyfile::UnsupportedFeature: Policyfile does not support chef-solo. Use chef-client local mode instead.

Platform:
---------
x86_64-darwin13.0

F

Failures:

  1) delivery::setup_spec doesn't do much right now
     Failure/Error: let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }

     Chef::PolicyBuilder::Policyfile::UnsupportedFeature:
       Policyfile does not support chef-solo. Use chef-client local mode instead.
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/policyfile.rb:72:in `initialize'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/dynamic.rb:155:in `new'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/dynamic.rb:155:in `select_implementation'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/dynamic.rb:74:in `load_node'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:465:in `load_node'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:375:in `client'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:142:in `node'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:107:in `converge'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:18:in `block in converge'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:17:in `tap'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:17:in `converge'
     # ./spec/unit/recipes/delivery_setup_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/delivery_setup_spec.rb:8:in `block (2 levels) in <top (required)>'
```

When I switch to `ChefSpec::ServerRunner.converge(described_recipe)` I get:

```
================================================================================
Chef encountered an error attempting to load the node data for "chefspec"
================================================================================

Unexpected Error:
-----------------
Chef::PolicyBuilder::Policyfile::ConfigurationError: Error loading policyfile from `policy_groups/local/policies/pantry': Net::HTTPServerException - 404 "Not Found "

Platform:
---------
x86_64-darwin13.0

F

Failures:

  1) delivery::setup_spec doesn't do much right now
     Failure/Error: let(:chef_run) { ChefSpec::ServerRunner.converge(described_recipe) }

     Chef::PolicyBuilder::Policyfile::ConfigurationError:
       Error loading policyfile from `policy_groups/local/policies/pantry': Net::HTTPServerException - 404 "Not Found "
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/policyfile.rb:271:in `rescue in policy'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/policyfile.rb:269:in `policy'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/policyfile.rb:263:in `run_list'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/policyfile.rb:291:in `validate_policyfile'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/policyfile.rb:116:in `finish_load_node'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/dynamic.rb:75:in `load_node'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:465:in `load_node'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:375:in `client'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:142:in `node'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:107:in `converge'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/server_runner.rb:69:in `converge'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:18:in `block in converge'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:17:in `tap'
     # /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:17:in `converge'
     # ./spec/unit/recipes/delivery_setup_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/delivery_setup_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Net::HTTPServerException:
     #   404 "Not Found "
     #   /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chef-12.10.24/lib/chef/http.rb:146:in `request'
```

In a moment of floundering, I pulled in `chefspec/policyfile` and got:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.13.21/lib/chef-dk/policyfile_services/install.rb:54:in `run': Policyfile not found at path /Users/clairemcquin/oc/delivery/cookbooks/delivery/Policyfile.rb (ChefDK::PolicyfileNotFound)
	from /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/policyfile.rb:32:in `setup!'
	from /Users/clairemcquin/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.7.0/lib/chefspec/policyfile.rb:60:in `block (2 levels) in <top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:357:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `block in run_hooks_with'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `run_hooks_with'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1679:in `with_suite_hooks'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /opt/chefdk/embedded/bin/rspec:22:in `load'
	from /opt/chefdk/embedded/bin/rspec:22:in `<main>'
```

Here's my spec_helper.rb:

```ruby
require 'chefspec'
require 'chefspec/berkshelf'

RSpec.configure do |config|
  config.platform = 'redhat'
  config.version = '7.0'
end
```

**Comment by mcquin** [comment]
My bad, it was picking up a configuration file that I didn't expect.

This moves me forward:
```ruby
ChefSpec::SoloRunner.new(use_policyfile: false, policy_name: nil, policy_group: nil)
```

**Comment by mivok** [comment]
For anyone else coming across this, one possible culprit appears to be berkshelf loading `.chef/knife.rb` when you `require 'chefspec/berkshelf'` (through a long chain of events).

To verify this is the case, temporarily add a `Chef::Log.warn(caller.join("\n"))` to your knife.rb or client.rb file that is being loaded when it shouldn't be, and look at the stack trace output when you run rspec, it should show the path of code that is loading the file when it shouldn't.

If chefspec/berkshelf is the issue in your case, set `ENV['BERKSHELF_CHEF_CONFIG'] = '/dev/null'` before requiring chefspec/berkshelf and it should go away.
