### ISSUE TITLE
windows_package matcher makes any source string lowercase

### ISSUE THREAD

**Issue by Xoph** [sethvargo/chefspec#729]
**Issue:**
The windows_package matcher is taking any string provided for the source parameter and making it lowercase.

**Environment:**
Windows 7 64-bit
Chef Development Kit Version: 0.15.16
chef-client version: 12.11.18
berks version: 4.3.5
kitchen version: 1.10.0

Code to reproduce:
**Here's the recipe:**
````
windows_package 'UnitTestPackage.exe' do
  action :install
  source 'C:\Temp\UnitTestPackage.exe'
end
````
**Here's the spec file:**
````
describe 'test::default' do
  # Run unit tests with mocked data for all relevant windows versions
  %w(2008R2 2012R2).each do |win_version|
    context "Test #{win_version}" do
      let(:chef_run) do
        ChefSpec::SoloRunner.new(platform: 'windows', version: win_version).converge(described_recipe)
      end

      it 'Installs the package' do
        expect(chef_run).to install_windows_package('UnitTestPackage.exe').with(source: 'C:\Temp\UnitTestPackage.exe')
      end

      it 'converges successfully' do
        expect { chef_run }.to_not raise_error
      end
    end
  end
end

````
**Here's the output:**
````
  1) server_connectivity_setup_pkg::aaa Test 2008R2 Installs the package
     Failure/Error: expect(chef_run).to install_windows_package('UnitTestPackage.exe').with(source: 'C:\Temp\UnitTestPac
kage.exe')

       expected "windows_package[UnitTestPackage.exe]" to have parameters:

         source "C:\\Temp\\UnitTestPackage.exe", was "c:\\temp\\unittestpackage.exe"
     # ./spec/unit/recipes/aaa_spec.rb:18:in `block (4 levels) in <top (required)>'

  2) server_connectivity_setup_pkg::aaa Test 2012R2 Installs the package
     Failure/Error: expect(chef_run).to install_windows_package('UnitTestPackage.exe').with(source: 'C:\Temp\UnitTestPac
kage.exe')

       expected "windows_package[UnitTestPackage.exe]" to have parameters:

         source "C:\\Temp\\UnitTestPackage.exe", was "c:\\temp\\unittestpackage.exe"
     # ./spec/unit/recipes/aaa_spec.rb:18:in `block (4 levels) in <top (required)>'
````

**Comment by Xoph** [comment]
I guess this could also be a Chef problem, not a ChefSpec problem... starting here though..

**Comment by Xoph** [comment]
It looks like it's due to the way Chef implemented the windows_package resource. The source string is converted to lowercase using Chef::Util::PathHelper.canonical_path. I guess the matcher should be updated for install_windows_package to always convert the expected to lowercase? Is that matcher in the Chef repo or the Windows cookbooks repo?

**Comment by sethvargo** [comment]
This is the expected behavior
