### ISSUE TITLE
Testing apt_update in spec

### ISSUE THREAD

**Issue by keltik85** [sethvargo/chefspec#780]
If my recipe is like this:

```
apt_update 'all platforms' do
  action :update
end

package 'python-pip'
```

I can test with ChefSpec wether or not the `python-pip` is installed, but how can I test if the update of apt-get is done?
```

This is my spec for the recipe:

require 'spec_helper'

describe 'django::install_pip' do
  context 'When all attributes are default, on an unspecified platform' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end

## i know that there is probably no function like this, nbut i tried anyway
    it 'the apt-get runs its update' do
      expect(chef_run).to update_apt_update('all platforms')
    end

    it 'the python pip package is installed' do
      expect(chef_run).to install_package('python-pip')
    end

  end
end
```

I get the following error log:

 2) django::install_pip When all attributes are default, on an unspecified platform the apt-get runs its update
```
    Failure/Error: runner.converge(described_recipe)

    ChefSpec::Error::MayNeedToSpecifyPlatform:
      It appears that Chef could not find the resource on the given platform. As of
      Chef 12.4, Chef conditionally loads resources based on the operating system
      being provisioned. Double-check the error below and ensure you did not make any
      typographical errors, and then continue reading.

      The default operating system for ChefSpec is "chefspec", which means Chef will
      not load many resources by default. For example, "dpkg_package" is not a
      resource that is available on the "chefspec" operating system just like
      "freebsd_package" is not available on the Windows operating system. As such,
      you may get a Chef::Exceptions::NoSuchResourceType when using ChefSpec's default
      options.

      You can specify the platform and version you would like ChefSpec to act like
      by specifying the platform and version like so:

          ChefSpec::SoloRunner.new(platform: 'ubuntu', version: '16.04')

      You can read more information in ChefSpec's README or the Fauxhai project:

          https://github.com/sethvargo/chefspec#configuration
          https://github.com/customink/fauxhai

      Here is the original error:

          Cannot find a resource for apt_update on chefspec version 0.6.1
    # ./spec/unit/recipes/install_pip_spec.rb:13:in `block (3 levels) in <top (required)>'
    # ./spec/unit/recipes/install_pip_spec.rb:21:in `block (3 levels) in <top (required)>'
    # ------------------
    # --- Caused by: ---
    # Chef::Exceptions::NoSuchResourceType:
    #   Cannot find a resource for apt_update on chefspec version 0.6.1
    #   C:/Users/myUsername/AppData/Local/Temp/chefspec20161120-1496-145ofsbfile_cache_path/cookbooks/django/recipes/install_pip.rb:6:in `from_file'
```

**Comment by tas50** [comment]
The error message is indicating that you need to mock an actual platform. If you do this it will execute the apt_update in your specs.  runner = ChefSpec::ServerRunner.new should be runner = ChefSpec::ServerRunner.new(platform: 'ubuntu', version: '16.04') and you should be good to go.
