### ISSUE TITLE
ChefSpec runner node missing default attributes set in the cookbook's "attributes" folder

### ISSUE THREAD

**Issue by trinitronx** [sethvargo/chefspec#790]
# Problem

Maybe I'm missing something basic because I'm fighting a cold & it's too late at night... but I seem to be hitting a strange bug.

When I set or initialize attributes in my recipe (or other dependent cookbooks), it appears that the `ChefSpec::SoloRunner.node` context does not include any of the default attributes set in those cookbooks in their `attributes/*.rb` files.

This problem is reproducible on my development laptop as well as on TravisCI, with ChefDK `0.13.21` and `1.1.16`.  It is also reproducible with the versions of Chef & ChefSpec in my cookbook's [`Gemfile`](https://github.com/trinitronx/lyraphase_workstation/blob/master/Gemfile#L20-L21)

## **A simple example:**

I see the issue in the most simple case when I create a recipe that checks whether it's node attributes are set with the correct type, and initialize these attributes in the cookbook's `attributes/` file.

A quick example can be seen in [this TravisCI job](https://travis-ci.org/trinitronx/lyraphase_workstation/builds/189460003).  Note that always in the debug messages printed from within the attributes file itself, and in the ChefSpec `context` where I set the `dmg` attribute to a preset for testing, [everything checks out OK](https://travis-ci.org/trinitronx/lyraphase_workstation/builds/189460003#L367-L373):

```ruby
[2017-01-06T10:04:24+00:00] WARN: INSIDE COOKBOOK ATTRIBUTES FILE: Loaded Attributes for: lyraphase_workstation::ableton_live Recipe
[2017-01-06T10:04:24+00:00] WARN: INSIDE COOKBOOK ATTRIBUTES FILE: is node['lyraphase_workstation']['ableton_live']['dmg'] a kind of Hash? true
[2017-01-06T10:04:24+00:00] WARN: INSIDE COOKBOOK ATTRIBUTES FILE: Class of node['lyraphase_workstation']['ableton_live']['dmg'] is: Chef::Node::ImmutableMash
[2017-01-06T10:04:24+00:00] WARN: INSIDE RECIPE: is node['lyraphase_workstation']['ableton_live']['dmg'] a kind of Hash? true
[2017-01-06T10:04:24+00:00] WARN: INSIDE RECIPE: Class of node['lyraphase_workstation']['ableton_live']['dmg'] is: Chef::Node::ImmutableMash
[2017-01-06T10:04:24+00:00] WARN: INSIDE RECIPE: debug_value of node['lyraphase_workstation']['ableton_live']['dmg']:
[2017-01-06T10:04:24+00:00] WARN: [["default", :not_present], ["env_default", :not_present], ["role_default", :not_present], ["force_default", :not_present], ["normal", {"source"=>"http://www.lyraphase.com/doc/installers/mac/ableton_live_suite_9.1.9_64.dmg", "checksum"=>"7a4da8531180afa8c7930a961289da1a0df567a8495e7ec205c7780f85dd0fda", "volumes_dir"=>"Ableton Live 9 Suite Installer", "dmg_name"=>"ableton_live_suite_9.1.9_64", "app"=>"Ableton Live 9 Suite", "type"=>"app"}], ["override", :not_present], ["role_override", :not_present], ["env_override", :not_present], ["force_override", :not_present], ["automatic", :not_present]]
```

However, in my particular ChefSpec [`context` for testing the recipe with default attributes as specified in the attributes file](https://github.com/trinitronx/lyraphase_workstation/blob/develop/spec/unit/recipes/ableton_live_spec.rb#L35), it is [set to `nil`, and the debug statements inside the recipe show this](https://travis-ci.org/trinitronx/lyraphase_workstation/builds/189460003#L384-L387):

```ruby
[2017-01-06T10:04:24+00:00] WARN: INSIDE RECIPE: is node['lyraphase_workstation']['ableton_live']['dmg'] a kind of Hash? false
[2017-01-06T10:04:24+00:00] WARN: INSIDE RECIPE: Class of node['lyraphase_workstation']['ableton_live']['dmg'] is: NilClass
[2017-01-06T10:04:24+00:00] WARN: INSIDE RECIPE: debug_value of node['lyraphase_workstation']['ableton_live']['dmg']:
[2017-01-06T10:04:24+00:00] WARN: [["default", :not_present], ["env_default", :not_present], ["role_default", :not_present], ["force_default", :not_present], ["normal", :not_present], ["override", :not_present], ["role_override", :not_present], ["env_override", :not_present], ["force_override", :not_present], ["automatic", :not_present]]
```

### Recipe Details
 - The recipe under test is: [`lyraphase_workstation::ableton_live`](https://github.com/trinitronx/lyraphase_workstation/blob/develop/recipes/ableton_live.rb)
 - The spec file for this is: [`spec/unit/recipes/ableton_live_spec.rb`](https://github.com/trinitronx/lyraphase_workstation/blob/develop/spec/unit/recipes/ableton_live_spec.rb)
 - An example ChefSpec failure log is: [TravisCI: trinitronx/lyraphase_workstation/builds/189460003](https://travis-ci.org/trinitronx/lyraphase_workstation/builds/189460003#L384-L426)

## **`include_recipe` example:**

I also see the problem when trying to use `include_recipe` where another cookbook is trying to use it's own attributes defined in the `attributes/*.rb` files.

Here is an example when including the `homebrew` cookbook:

```
$ bundle exec rspec
[... SNIP ...]
================================================================================
Recipe Compile Error in /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/lyraphase_workstation/recipes/gpg21.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/homebrew/recipes/default.rb:30:in `block in from_file'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `instance_eval'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `build'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/homebrew/recipes/default.rb:29:in `from_file'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:292:in `block in include_recipe'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `each'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `include_recipe'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/homebrew/recipes/install_formulas.rb:20:in `from_file'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:292:in `block in include_recipe'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `each'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `include_recipe'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/lyraphase_workstation/recipes/gpg21.rb:28:in `from_file'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
  /var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:185:in `load'

Relevant File Content:
----------------------
/var/folders/f0/49hvn6tn71723n4840d566vm0000gn/T/d20170106-4353-1xqhqow/cookbooks/homebrew/recipes/default.rb:

 23:  Chef::Recipe.send(:include, Homebrew::Mixin)
 24:
 25:  homebrew_go = "#{Chef::Config[:file_cache_path]}/homebrew_go"
 26:
 27:  Chef::Log.debug("Homebrew owner is '#{homebrew_owner}'")
 28:
 29:  remote_file homebrew_go do
 30>>   source node['homebrew']['installer']['url']
 31:    checksum node['homebrew']['installer']['checksum'] unless node['homebrew']['installer']['checksum'].nil?
 32:    mode 00755
 33:  end
 34:
 35:  execute 'install homebrew' do
 36:    command homebrew_go
 37:    environment lazy { { 'HOME' => ::Dir.home(homebrew_owner), 'USER' => homebrew_owner } }
 38:    user homebrew_owner
 39:    not_if { ::File.exist? '/usr/local/bin/brew' }

F
[... SNIP ...]
```

The line it's complaining about in the stacktrace (`lyraphase_workstation/recipes/gpg21.rb:28:in 'from_file'`) just has `include_recipe "homebrew::install_formulas"`.

When debugging the issue, I even tried initializing the missing attribute myself to try and avoid the `undefined method '[]' for nil:NilClass` error.  However, it still appears indicating something very strange going on with the node attributes in the ChefSpec run context.

I do have the dependency set [in my `metadata.rb`](https://github.com/trinitronx/lyraphase_workstation/blob/add-gpg21-hacks-recipe/metadata.rb):

```ruby
supports         'mac_os_x'
depends          'homebrew' # For homebrew_tap, homebrew_cask LWRP
depends          'dmg'
depends          'osx' # For osx_defaults LWRP
depends          'sprout-base'  # For `libraries/directory#recursive_directories()` function
depends          'plist' # For `plist_file` LWRP (used in lyraphase_workstation::airfoil recipe)
```

As well as in [my cookbook's `Berksfile`](https://github.com/trinitronx/lyraphase_workstation/blob/add-gpg21-hacks-recipe/Berksfile):

```ruby
#source 'http://api.berkshelf.com'
source "https://supermarket.chef.io"

group :integration do
  cookbook "minitest-handler"
end

cookbook 'sprout-base', '~> 0.1', :github => 'pivotal-sprout/sprout-base'
cookbook 'osx', '~> 0.1.0', :github => 'pivotal-sprout/osx'

cookbook 'plist', '~> 0.9', :github => 'trinitronx/chef-plist', rel: 'vendor/cookbooks/plist', :branch => 'add-chefspec-matchers'

cookbook 'homebrew', '>= 1.13.0'

metadata
```

I also have the berkshelf include in `spec_helper.rb`:

`spec/spec_helper.rb`:
```ruby
require 'chefspec'
require 'chefspec/berkshelf'

## Gets rid of const redefinition warnings
def create_singleton_struct name, fields
  if Struct::const_defined? name
    Struct.const_get name
  else
    Struct.new name, *fields
  end
end

# Require all our libraries
Dir['libraries/*.rb'].each { |f| require File.expand_path(f) }

RSpec.configure do |config|
  config.platform = 'mac_os_x'
  config.version = '10.9.2'
  config.before { stub_const('ENV', ENV.to_hash.merge('SUDO_USER' => 'brubble')) }
end

at_exit { ChefSpec::Coverage.report! }
```

### Recipe Details
 - The recipe under test is: [`lyraphase_workstation::gpg21`](https://github.com/trinitronx/lyraphase_workstation/blob/add-gpg21-hacks-recipe/recipes/gpg21.rb)
 - The spec file for this is: [`spec/unit/recipes/gpg21_spec.rb`](https://github.com/trinitronx/lyraphase_workstation/blob/add-gpg21-hacks-recipe/spec/unit/recipes/gpg21_spec.rb)
 - An example ChefSpec failure log is: [in this gist: trinitronx/9a94c1dcd1d26f57ae76cf56981f0a89](https://gist.github.com/trinitronx/9a94c1dcd1d26f57ae76cf56981f0a89)

**Comment by trinitronx** [comment]
Ok, so this was a tricky & hard one to track down... but it turns out it was my fault!

# Solution

As it turns out, I had accidentally re-defined the top level Hash key attribute as `{}` (which would be the empty `Hash` in Ruby) in another file.  Without realizing that I had 2 separate `attributes/*.rb` files that were re-defining this Hash key and one was overwriting the other during Chef's compilation phase.

After I searched for the hash key in my cookbook, it turned up 2 files matching the pattern:

```bash
$ ag "\['lyraphase_workstation'\]\['ableton_live'\]" attributes/
attributes/ableton_live.rb
1:default['lyraphase_workstation']['ableton_live'] = {}
2:default['lyraphase_workstation']['ableton_live']['dmg']['source']      = 'http://www.lyraphase.com/doc/installers/mac/ableton_live_suite_9.7_64.dmg'
3:default['lyraphase_workstation']['ableton_live']['dmg']['checksum']    = "35fa16a2c703d458fc005413e81e7fccd3ebf18eff5bffea91eb9165db42c400"
4:default['lyraphase_workstation']['ableton_live']['dmg']['volumes_dir'] = "Ableton Live 9 Suite Installer"
5:default['lyraphase_workstation']['ableton_live']['dmg']['dmg_name']    = 'ableton_live_suite_9.7_64'
6:default['lyraphase_workstation']['ableton_live']['dmg']['app']         = 'Ableton Live 9 Suite'
7:default['lyraphase_workstation']['ableton_live']['dmg']['type']        = 'app'

attributes/ableton_live_options.rb
1:default['lyraphase_workstation']['ableton_live'] = {}
2:default['lyraphase_workstation']['ableton_live']['options'] = []
4:default['lyraphase_workstation']['ableton_live']['managed_versions'] = nil
```

So, the second alphabetical one in the list was `attributes/ableton_live_options.rb` which redefined the top-level `['lyraphase_workstation']['ableton_live']` to `{}`.  So when the debug statements printed in the `attributes/*` files, they were always showing that it was set correctly at that point in time.  Then later the next attribute file in alphabetical order was loaded & redefined it, so in the recipe it was shown as nil.
