### ISSUE TITLE
Problem in 6.0.0: No port in :port range 8889 is available

### ISSUE THREAD

**Issue by atheiman** [sethvargo/chefspec#813]
below is some jenkins output of chefspec failures we're getting with 6.0.0. Reverting to 5.4.0 fixes the problem. We use the `parallel_tests` gem to run groups of specs in parallel for this cookbook.

You can see the full bundle and stacktrace in this gist: https://gist.github.com/atheiman/4ac3dd2db120ed5e7fc4e04d8948c3dc

```
+ bundle exec rake 'parallel:spec[8]'
8 processes for 28 specs, ~ 3 specs per process

An error occurred in a `before(:suite)` hook.
Failure/Error:
  raise Errno::EADDRINUSE,
    "No port in :port range #{options[:port]} is available"

Errno::EADDRINUSE:
  Address already in use - No port in :port range 8889 is available
# /home/jenkins/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chef-zero-5.3.0/lib/chef_zero/server.rb:307:in `start_background'
# /home/jenkins/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chefspec-6.0.0/lib/chefspec/zero_server.rb:31:in `setup!'
# /home/jenkins/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chefspec-6.0.0/lib/chefspec/zero_server.rb:136:in `block (2 levels) in <top (required)>'
```

**Comment by kamaradclimber** [comment]
Also impacted by this symptom. Our tests are launched by jenkins and can have multiple rspec running at the same time.

**Comment by atheiman** [comment]
This seems to be fixed for us, Thanks!
